services:
  db:
    image: postgres:latest
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - './data/docker/volumes/postgres/:/var/lib/postgresql'
  cognito:
    image: jagregory/cognito-local
    ports:
      - '${COGNITO_PORT:-9229}:9229'
    volumes:
      - './data/docker/volumes/cognito:/app/.cognito'
