name: CI workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PORT: 5000
      DB_HOST: localhost
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 123456
      DB_NAME: db_test
      BASE_APP_URL: http://localhost:5000/api/v1

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.10.9

      - name: Build and test with coverage
        run: npm run test:cov
